name: Workflow_1 - Increase App Versions on PR merged to DEVELOP

on:
  workflow_dispatch:   # Allow to run manually
  pull_request:
    types: [closed]    # Trigger when a pull request is closed
    branches:
      - develop

permissions:
  contents: write

jobs:
  increment-version-and-update-csproj:
    # Not trigger workflow when PR was just closed manually
    if: > 
      github.event.pull_request.merged == true && 
      github.event.pull_request.base.ref == 'develop' && 
      github.event.pull_request.head.ref != 'release'
    runs-on: runner02

    env:
      PROJECTS_LIST: |
        SERVICE_A=./SERVICE_A/src/Company.SERVICE_A.Api/Company.SERVICE_A.Api.csproj
        SERVICE_B=./ServiceB/src/Company.ServiceB.Api/Company.ServiceB.Api.csproj
        

    steps:
      - name: Checkout Develop Branch with Token  # Step moved up
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.HYBRID_GITHUB_ACTIONS_BYPASS_PR }}

      - name: Authentication via Token and Fetching
        id: auth-stage
        env:
          token: ${{ secrets.HYBRID_GITHUB_ACTIONS_BYPASS_PR }}
        run: |
          git config --local user.email "action@companyproject.com"
          git config --local user.name "GitHub Action"
          git config --local github.user jenkins
          git config --local github.token ${token}
          git config --local credential.helper 'store --file .git/credentials'
          echo "https://${token}:x-oauth-basic@github.companyproject.com" > .git/credentials
          echo "============  Show Config Local  ================"
          git config --local --list

      - name: Verify Versions
        id: verify_versions
        run: |
          #!/usr/bin/env bash
          set -e

          # Debug: Print the projects list
          echo "Projects list:"
          echo "$PROJECTS_LIST"

          # Parse the PROJECTS_LIST into an associative array
          declare -A PROJECTS
          while IFS='=' read -r key value; do
            # Skip empty lines
            [ -z "$key" ] && continue
            PROJECTS[$key]=$value
          done < <(echo "$PROJECTS_LIST")

          # Use the SERVICE_A project as the source
          SOURCE_PROJECT="SERVICE_A"
          SOURCE_CSPROJ="${PROJECTS[$SOURCE_PROJECT]}"

          # Extract current App Version from source project
          CURRENT_VERSION=$(awk -F '[<>]' '/<Version>/{print $3}' "$SOURCE_CSPROJ")
          if [ -z "$CURRENT_VERSION" ]; then
            echo "No <Version> tag found in $SOURCE_CSPROJ"
            exit 1
          fi

          # Verify that all projects have the same version
          for PROJECT in "${!PROJECTS[@]}"; do
            CSPROJ_PATH="${PROJECTS[$PROJECT]}"
            PROJECT_VERSION=$(awk -F '[<>]' '/<Version>/{print $3}' "$CSPROJ_PATH")

            if [ "$PROJECT_VERSION" != "$CURRENT_VERSION" ]; then
              echo "Version mismatch detected in $CSPROJ_PATH"
              echo "Expected: $CURRENT_VERSION, Found: $PROJECT_VERSION"
              exit 1
            fi
          done

          echo "All project versions match: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment Versions for All Projects
        id: increment_versions
        run: |
          #!/usr/bin/env bash
          set -e
          
          # Load CURRENT_VERSION from environment
          CURRENT_VERSION="${CURRENT_VERSION}"

          # Rebuild the PROJECTS array
          declare -A PROJECTS
          while IFS='=' read -r key value; do
            [ -z "$key" ] && continue
            PROJECTS[$key]=$value
          done < <(echo "$PROJECTS_LIST")

          # Increment the BUILD component of MAJOR.MINOR.PATCH.BUILD
          IFS='.' read -r MAJOR MINOR PATCH BUILD <<< "$CURRENT_VERSION"
          BUILD=$((BUILD + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH.$BUILD"

          echo "Incrementing all projects from $CURRENT_VERSION to $NEW_VERSION"

          # Update all projects with the new version
          for PROJECT in "${!PROJECTS[@]}"; do
            CSPROJ_PATH="${PROJECTS[$PROJECT]}"
            awk -v newver="$NEW_VERSION" '/<Version>/{gsub(/>[^<]+</,">"newver"<")}1' "$CSPROJ_PATH" > temp.csproj
            mv temp.csproj "$CSPROJ_PATH"
          done

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          # Load NEW_VERSION from environment
          NEW_VERSION="${NEW_VERSION}"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Only commit if there are actually changes staged
          if ! git diff --cached --quiet; then
            git commit -m "Incremented App Version: $NEW_VERSION"
            git push origin HEAD:${GITHUB_REF}
          else
            echo "No changes to commit."
          fi
